#!/bin/bash

set -eu -o pipefail

export INFLUXDB_INIT_MODE=$INFLUXDB_INIT_MODE
export INFLUXDB_INIT_USERNAME=$INFLUXDB_INIT_USERNAME
export INFLUXDB_INIT_PASSWORD=$INFLUXDB_INIT_PASSWORD
export INFLUXDB_INIT_ORG=$INFLUXDB_INIT_ORG
export INFLUXDB_INIT_BUCKET=$INFLUXDB_INIT_BUCKET
export INFLUXDB_INIT_RETENTION=$INFLUXDB_INIT_RETENTION
export INFLUXDB_INIT_ADMIN_TOKEN=$INFLUXDB_INIT_ADMIN_TOKEN
export INFLUXDB_INIT_PORT=$INFLUXDB_INIT_PORT
export INFLUXDB_INIT_HOST=$INFLUXDB_INIT_HOST

influx setup --skip-verify --bucket ${INFLUXDB_INIT_BUCKET} --retention ${INFLUXDB_INIT_RETENTION} --token ${INFLUXDB_INIT_ADMIN_TOKEN} --org ${INFLUXDB_INIT_ORG} --username ${INFLUXDB_INIT_USERNAME} --password ${INFLUXDB_INIT_PASSWORD} --host http://${INFLUXDB_INIT_HOST}:8086 --force