version: "3"
services:
  portainer:
    image: portainer/portainer-ce
    ports:
      - 9443:9443
    volumes:
      - ./portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/sec/portainer.txt:/run/secrets/admin_pass
    restart: unless-stopped
    command: --admin-password-file /run/secrets/admin_pass